name: Bug Report
description: This is the bug reporting form
labels: [bug]
body:
  - type: input
    id: program-name
    attributes:
      label: Program Name
      description: Name of the program where the bug occurred.
      placeholder: e.g. NotificationApp v2
    validations:
      required: true

  - type: textarea
    id: bug-details
    attributes:
      label: What issue did you encounter?
      description: Please describe the issue that occurred.
    validations:
      required: true

  - type: input
    id: operating-system
    attributes:
      label: Operating System
      placeholder: e.g. Windows 11 24H2
    validations:
      required: true

  - type: checkboxes
    id: chest-list
    attributes:
      label: Chest List
      options:
        - label: The issues encountered are not those listed on the program page.

  - type: textarea
    id: additional-info
    attributes:
      label: Additional Info
      placeholder: None
      value: None
