name: Bug Report
description: This is the bug reporting form
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        **What bug did you encounter?**  
        Please include as many details about the bug as possible.

  - type: textarea
    id: bug-details
    attributes:
      label: What bug did you encounter?
      description: Please include as many details about the bug as possible.
      placeholder: Describe the bug here...

  - type: input
    id: program-name
    attributes:
      label: Program Name
      description: Please include the name of the program in which the bug occurs.
      placeholder: NotificationApp v2

  - type: input
    id: operating-system
    attributes:
      label: Operating System
      placeholder: Windows 11 24H2

  - type: checkboxes
    id: chest-list
    attributes:
      label: Chest List
      options:
        - label: The issues encountered are not those listed on the program page.

  - type: textarea
    id: additional-info
    attributes:
      label: Additional Info
      description: Any other information you'd like to share.
      placeholder: None
      value: None
