name: Bug Report
description: This is the bug reporting form
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        ## 🐞 What bug did you encounter?
        Please include as many details about the bug as possible.

  - type: textarea
    id: bug-details
    attributes:
      label: Bug Description
      description: Describe the bug in detail, including steps to reproduce if possible.
      placeholder: e.g. The app crashes when clicking the save button.
    validations:
      required: true

  - type: input
    id: program-name
    attributes:
      label: Program Name
      description: Name of the program where the bug occurred.
      placeholder: NotificationApp v2
    validations:
      required: true

  - type: input
    id: operating-system
    attributes:
      label: Operating System
      placeholder: Windows 11 24H2
    validations:
      required: true

  - type: checkboxes
    id: chest-list
    attributes:
      label: Chest List
      options:
        - label: The issues encountered are not those listed on the program page.

  - type: textarea
    id: additional-info
    attributes:
      label: Additional Info
      description: Any other information you'd like to share.
      placeholder: None
      value: None
